name: Build & Deploy RecipeBox Frontend

on:
  push:
    branches:
      - main
    paths:
      - recipe-box-frontend/**
      - .github/workflows/build_deploy_rcb_fe.yml
  pull_request:
    branches:
      - main
    paths:
      - recipe-box-frontend/**
      - .github/workflows/build_deploy_rcb_fe.yml
  workflow_dispatch: 
    inputs:
      run_deploy:
        type: boolean
        default: true
        required: true
        description: Should the frontend app be deployed?

# Azure login
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: deploy
    steps:
      - name: Worker - Checkout repo
        uses: actions/checkout@v4

      - name: Worker - Maven setup
        run: |
          sudo apt -qq update
          sudo apt -qq install maven -y

      # - name: Worker - Azure login
      #   if: ${{ github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.run_deploy == 'true')}}
      #   uses: azure/login@v2
      #   with:
      #     client-id:       ${{ secrets.AZURE_CLIENT_ID }}
      #     tenant-id:       ${{ secrets.AZURE_TENANT_ID }}
      #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            
      # - name: Worker - Fetch Remote IP address
      #   if: ${{ github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.run_deploy == 'true')}}
      #   working-directory: .github/workflows/scripts
      #   run: bash ./fetch_ip.sh "rcb-public-ip"

      - name: Worker - Build web app using Maven
        env:
          REACT_APP_BACKEND_URL: "https://${{ vars.DOMAIN_NAME }}:8080"
        run: mvn install -B -e
        working-directory: recipe-box-frontend

      - name: Worker - Upload site as artifact
        if: ${{ github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.run_deploy == 'true')}}
        uses: actions/upload-artifact@v4
        with:
          name: production-rcb-fe
          path: ./recipe-box-frontend/target

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.run_deploy == 'true')}}
    environment: deploy # Azure login

    steps:
      - name: Worker - Checkout repo
        uses: actions/checkout@v4

      - name: Worker - Azure login
        uses: azure/login@v2
        with:
          client-id:       ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id:       ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            
      - name: Worker - Fetch Remote IP address
        working-directory: .github/workflows/scripts
        run: bash ./fetch_ip.sh "rcb-public-ip"

      - name: Worker - Config SSH
        working-directory: .github/workflows/scripts
        env:
          SSH_PRIVATE_KEY:    ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_ADMIN_USERNAME: ${{ secrets.SSH_ADMIN_USERNAME }}
        run: bash ./worker_config_ssh.sh "rcb"

      - name: Remote - Config nginx
        continue-on-error: true
        working-directory: .github/workflows/scripts
        env:
          GITHUB_FE_SITE_DOMAIN: ${{ vars.DOMAIN_NAME }}
          GITHUB_ADMIN_USERNAME: ${{ secrets.SSH_ADMIN_USERNAME }}
        run: bash ./configure_nginx_remote.sh

      - name: Worker - Download build site
        uses: actions/download-artifact@v4
        with:
          name: production-rcb-fe
          path: ./rcb-webapp

      - name: Worker - Move built site to remote
        run: scp -r ./rcb-webapp/* rcb:/var/www/${{ vars.DOMAIN_NAME }}/html

      - name: Remote - Restart nginx
        run : ssh rcb 'sudo systemctl restart nginx'

      - name: Cloudflare - Update / Create DNS Entry (domain)
        uses: everpcpc/cloudflare-dns-action@v1
        with:
          type: "A"
          name: "${{ vars.DOMAIN_NAME }}"
          content: "${{ env.IP_ADDRESS }}"
          ttl: 1
          proxied: false
          token: ${{ secrets.CLOUDFLARE_TOKEN }}
          zone: ${{ secrets.CLOUDFLARE_ZONE }}
        
      - name: Cloudflare - Update / Create DNS Entry (www.domain)
        uses: everpcpc/cloudflare-dns-action@v1
        with:
          type: "A"
          name: "www.${{ vars.DOMAIN_NAME }}"
          content: "${{ env.IP_ADDRESS }}"
          ttl: 1
          proxied: false
          token: ${{ secrets.CLOUDFLARE_TOKEN }}
          zone: ${{ secrets.CLOUDFLARE_ZONE }}
