name: Build & Deploy RecipeBox Backend

on:
  push:
    branches:
      - main
    paths:
      - recipe-box-backend/**
      - .github/workflows/build_deploy_rcb_be.yml
  pull_request:
    branches:
      - main
    paths:
      - recipe-box-backend/**
      - .github/workflows/build_deploy_rcb_be.yml
  workflow_dispatch: 
    inputs:
      run_deploy:
        type: boolean
        default: true
        description: Should the backend app be deployed?
        required: true

# Azure login
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download and setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Download and install maven
        run: |
          sudo apt -qq update
          sudo apt -qq install maven -y
      - name: Package server app using maven
        # run: mvn package -B -q -DskipTests=true # TODO: remove skipping tests
        run: mvn package -B -q
        working-directory: recipe-box-backend

      - name: Upload generated bundle as an artifact
        if: ${{ github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.run_deploy == 'true')}}
        uses: actions/upload-artifact@v4
        with:
          name: production-rcb-be
          path: ./recipe-box-backend/target/*.jar

  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.run_deploy == 'true')}}
    environment: deploy
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login with Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
      - name: Fetch server public IP address
        working-directory: .github/workflows/scripts
        run: bash ./fetch_ip.sh

      - name: Config SSH connection on the Github Worker
        working-directory: .github/workflows/scripts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_ADMIN_USERNAME: ${{ secrets.SSH_ADMIN_USERNAME }}
        run: bash ./worker_config_ssh.sh

      - name: Download built package
        uses: actions/download-artifact@v4
        with:
          name: production-rcb-be

      - name: Install dependencies on the remote server and start a screen
        working-directory: .github/workflows/scripts
        run: bash ./be_remote_configure.sh

      - name: Move backend package to server
        run: scp ./recipe-box-backend-0.0.1-SNAPSHOT.jar rcb:~/rcb-be/

      - name: Run backend on screen
        run: | 
          ssh rcb <<CONTENT
            lines_to_add=("export DB_URL=\"${{ vars.DB_URL }}\"" "export DB_USERNAME=\"${{ vars.DB_USERNAME }}\"" "export DB_PASSWORD=\"${{ secrets.DB_PASSWORD }}\"")

            for line in "\${lines_to_add[@]}"; do
              if ! sudo grep -Fxq "\$line" ~/.bashrc; then
                echo "\$line" | sudo tee -a ~/.bashrc > /dev/null
              fi
            done

            source ~/.bashrc

            screen -S "rcb-be" -X stuff "java -jar ~/rcb-be/recipe-box-backend-0.0.1-SNAPSHOT.jar$(printf \\r)"
          CONTENT

