name: Build & Deploy RecipeBox Frontend

on:
  push:
    branches:
      - main
    paths:
      - recipe-box-frontend/**
      - .github/workflows/build_deploy_rcb_fe.yml
  pull_request:
    branches:
      - main
    paths:
      - recipe-box-frontend/**
      - .github/workflows/build_deploy_rcb_fe.yml
  workflow_dispatch: 
    inputs:
      run_deploy:
        type: boolean
        default: true
        description: Should the frontend app be deployed?
        required: true

# Azure login
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download and install maven
        run: sudo apt -qq update & sudo apt -qq install maven -y

      - name: Build web app using maven
        run: mvn install -B -q
        working-directory: recipe-box-frontend

      - name: Upload generated bundle as an artifact
        if: ${{ github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.run_deploy == 'true')}}
        uses: actions/upload-artifact@v4
        with:
          name: production-rcb-fe
          path: ./recipe-box-frontend/target

  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.run_deploy == 'true')}}
    environment: deploy # Azure login
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login with Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            
      - name: Fetch server public IP address
        working-directory: .github/workflows/scripts
        run: chmod +x fetch_ip.sh & sudo ./fetch_ip.sh

      - name: Config SSH connection on the Github Worker
        working-directory: .github/workflows/scripts
        run: chmod +x fetch_ip.sh & sudo ./worker_config_ssh.sh

      - name: Config nginx on remote
        continue-on-error: true
        working-directory: .github/workflows/scripts
        env:
          GITHUB_FE_SITE_DOMAIN: ${{ vars.DOMAIN_NAME }}
          GITHUB_ADMIN_USERNAME: ${{ secrets.SSH_ADMIN_USERNAME }}
        run: chmod +x fetch_ip.sh & sudo ./configure_nginx_remote.sh

      - name: Download built site
        uses: actions/download-artifact@v4
        with:
          name: production-rcb-fe
          path: ./rcb-webapp

      - name: Move built site to server
        run: scp -r ./rcb-webapp/* rcb:/var/www/${{ vars.DOMAIN_NAME }}/html

      - name: Restart Nginx
        run : ssh rcb 'sudo systemctl restart nginx'

      - name: Create / Update DNS Records on domain to point to server (domain)
        uses: everpcpc/cloudflare-dns-action@v1
        with:
          type: "A"
          name: "${{ vars.DOMAIN_NAME }}"
          content: "${{ env.IP_ADDRESS }}"
          ttl: 1
          proxied: false
          token: ${{ secrets.CLOUDFLARE_TOKEN }}
          zone: ${{ secrets.CLOUDFLARE_ZONE }}
        
      - name: Create / Update DNS Records on domain to point to server (www.domain)
        uses: everpcpc/cloudflare-dns-action@v1
        with:
          type: "A"
          name: "www.${{ vars.DOMAIN_NAME }}"
          content: "${{ env.IP_ADDRESS }}"
          ttl: 1
          proxied: false
          token: ${{ secrets.CLOUDFLARE_TOKEN }}
          zone: ${{ secrets.CLOUDFLARE_ZONE }}
