name: Build & Deploy RecipeBox Backend
on:
  push:
    branches:
      - main
    paths:
      - recipe-box-backend/**
      - .github/workflows/build_deploy_rcb_be.yml
  pull_request:
    branches:
      - main
    paths:
      - recipe-box-backend/**
      - .github/workflows/build_deploy_rcb_be.yml
  workflow_dispatch: 
    inputs:
      run_deploy:
        type: boolean
        default: true
        required: true
        description: Should the backend app be deployed?

# Azure login
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Worker - Checkout repo
        uses: actions/checkout@v4

      - name: Worker - Java setup
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Worker - Maven setup
        run: |
          sudo apt -qq update
          sudo apt -qq install maven -y

      - name: Worker - Package .jar using maven
        working-directory: recipe-box-backend
        run: mvn package -B -e

      - name: Worker - Upload .jar as artifact
        if: ${{ github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.run_deploy == 'true')}}
        uses: actions/upload-artifact@v4
        with:
          name: production-rcb-be
          path: ./recipe-box-backend/target/*.jar

  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.run_deploy == 'true')}}
    environment: deploy
    needs: build

    steps:
      - name: Worker - Checkout repo
        uses: actions/checkout@v4

      - name: Worker - Azure login
        uses: azure/login@v2
        with:
          client-id:       ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id:       ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
      - name: Worker - Fetch Remote IP address
        working-directory: .github/workflows/scripts
        run: bash ./fetch_ip.sh "rcb-public-ip"

      - name: Worker - Config SSH
        working-directory: .github/workflows/scripts
        env:
          SSH_PRIVATE_KEY:    ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_ADMIN_USERNAME: ${{ secrets.SSH_ADMIN_USERNAME }}
        run: bash ./worker_config_ssh.sh "rcb"

      - name: Worker - Download .jar
        uses: actions/download-artifact@v4
        with:
          name: production-rcb-be

      - name: Remote - Install dependencies & start screen
        working-directory: .github/workflows/scripts
        run: bash ./be_remote_configure.sh

      - name: Worker - Move .jar to remote
        run: scp ./recipe-box-backend-0.0.1-SNAPSHOT.jar rcb:~/rcb-be/

      - name: Worker - Move backend start script to remote
        run: scp .github/workflows/scripts/start_backend.sh rcb:~/rcb-be/

      - name: Remote - Run backend on screen
        run: ssh rcb 'bash ~/rcb-be/start_backend.sh "${{ vars.DB_URL }}" "${{ vars.DB_USERNAME }}" "${{ secrets.DB_PASSWORD }}" "${{ vars.BACKEND_SERVER_PORT }}"'
