name: Build & Deploy RecipeBox Frontend

on:
    push:
        # branches:
        #     - main
    pull_request:
        # branches:
        #     - main

# for logging in w/ azure
permissions:
  id-token: write
  contents: read

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Download and setup node.js
          uses: actions/setup-node@v4
          with:
            node-version: 'lts/*'

        - name: Install bun
          uses: oven-sh/setup-bun@v2
          with:
            bun-version: 'latest'

        - name: Install dependencies using bun (faster)
          run: bun i
          working-directory: ./recipe-box-frontend/src/main/frontend

        - name: Build web app
          run: npm run build
          working-directory: ./recipe-box-frontend/src/main/frontend

        - name: Upload generated bundle as an artifact
          uses: actions/upload-artifact@v4
          with:
            name: production-rcb-fe
            path: ./recipe-box-frontend/target

    deploy:
      runs-on: ubuntu-latest
      environment: deploy # for logging in w/ azure
      needs: build

      steps:
        - name: Download build artifact
          uses: actions/download-artifact@v4
          with:
            name: production-rcb-fe
            path: ./rcb-webapp
          
        - name: Generate temp SSH private key file
          run: | 
            mkdir ~/.ssh
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            chmod 700 ~/.ssh

        - name: Login with Azure
          uses: azure/login@v2
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

        - name: Fetch server public IP address
          run: |
            cmd_output=$(az network public-ip show \
              --resource-group apprenticeship-2024-rg \
              --name rcb-public-ip \
              --query "ipAddress" \
              --output tsv 2> ./ip_fetch_error.log) || \
              { \
                echo "Fetching IP Address failed! Please check the error."; \
                cat ./ip_fetch_error.log; \
                exit 1; \
              } \
            
            if [ -z "$cmd_output" ]; then
              echo "Fetching IP Address failed! Please check that the infrastructure was deployed and the query is correct."
              exit 1
            else
              echo "IP_ADDRESS=$cmd_output" > $GITHUB_ENV
              echo "Successfully fetched IP address into IP_ADDRESS"
            fi
        - name: Trust server and fetch public key
          run: |
            ssh-keyscan -p 22 $IP_ADDRESS >> ~/.ssh/known_hosts

        - name: Create ssh host
          run: |
            cat >> ~/.ssh/config <<CONTENT
            Host rcb
              HostName $IP_ADDRESS
              User ${{ secrets.SSH_ADMIN_USERNAME }}
              IdentityFile ~/.ssh/id_rsa
            CONTENT

        - name: Install nginx (if not installed)
          run: |
            ssh rcb 'sudo apt update'


        
# az network public-ip show --resource-group apprenticeship-2024-rg --name rcb-public-ip --query "ipAddress" --output tsv
